[Icon Theme]
Name=Material-Tela
Inherits=hicolor
Comment=Tela folders + Monochrome accent apps

DisplayDepth=32
FollowsColorScheme=true
Example=x-directory-normal

KDE-Extensions=.svg

Directories=actions/scalable,actions/symbolic,apps/16,apps/scalable,apps/symbolic,categories/scalable,categories/symbolic,devices/scalable,devices/symbolic,emblems/scalable,emblems/symbolic,emotes/symbolic,legacy/symbolic,places/scalable,places/symbolic,mimetypes/scalable,mimetypes/scalable-outlined,mimetypes/symbolic,status/scalable,status/symbolic,preferences/scalable,preferences/symbolic,ui/symbolic

[actions/scalable]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[actions/symbolic]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[apps/16]
Size=128
Context=Applications
Type=Scalable
MinSize=8
MaxSize=24

[apps/scalable]
Size=128
Context=Applications
Type=Scalable
MinSize=25
MaxSize=512

[apps/symbolic]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[categories/scalable]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[categories/symbolic]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[devices/scalable]
Size=128
Context=Devices
Type=Scalable
MinSize=8
MaxSize=128

[devices/symbolic]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[emblems/scalable]
Size=128
Context=Actions
Type=Scalable
MinSize=16
MaxSize=128

[emblems/symbolic]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[legacy/symbolic]
Context=Legacy
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[emotes/symbolic]
Context=Emotes
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[places/scalable]
Context=Places
Size=64
MinSize=33
MaxSize=512
Type=Scalable

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[mimetypes/scalable]
Size=512
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/scalable-outlined]
Size=512
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/symbolic]
Context=MimeTypes
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[status/scalable]
Context=Status
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[status/symbolic]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[preferences/scalable]
Context=Applications
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[preferences/symbolic]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[ui/symbolic]
Context=UI
Size=16
MinSize=8
MaxSize=512
Type=Scalable
